/**
 * Built-in skills shipped with Dodo. These are baked into the bundle as
 * static markdown — no R2 lookup, no DO query. The model sees them in the
 * `<available_skills>` manifest like any other skill and loads them on
 * demand via the `skill` tool.
 *
 * Each entry must include the same fields a parsed SKILL.md file would
 * produce: `name`, `description`, `body`. Add new built-ins by appending
 * to BUILTIN_SKILLS.
 *
 * Personal skills with the same name override built-ins (see mergeSkills
 * precedence in skill-registry.ts). That lets users tweak a built-in
 * without forking Dodo.
 */

import type { Skill } from "./skill-registry";

const BUILTIN_SKILLS: Array<Pick<Skill, "name" | "description" | "body">> = [
  {
    name: "dodo-self",
    description:
      "Reference for Dodo's own architecture — sessions, Durable Objects, R2 spillage, the agentic loop, and how subagents (explore/task) work. Load when the user asks how Dodo works internally, where data lives, or how to extend the agent.",
    body: [
      "# Dodo internals reference",
      "",
      "Dodo runs on Cloudflare Workers with three Durable Objects:",
      "- **CodingAgent** — one per session. Owns the chat loop, workspace, and tool execution.",
      "- **UserControl** — one per user (`idFromName(email)`). Holds config, memory, skills, MCP setup.",
      "- **SharedIndex** — global singleton. Tracks users, host allowlist, models cache.",
      "",
      "## Storage",
      "- Per-DO SQLite holds structured data (config, sessions, skills, memory, tasks).",
      "- R2 (`WORKSPACE_BUCKET`) holds workspace file spill, attachments, and bundled skill assets.",
      "- No KV, no D1.",
      "",
      "## Agentic loop",
      "- Lives in `src/coding-agent.ts:onChatMessage()`. Runs `streamText({ maxSteps: 1 })` per iteration.",
      "- Per iteration: detect doom loops (same tool+args 3×), check token budget, trigger compaction at 50%.",
      "- System prompt assembled by `getSystemPrompt()` at the same file.",
      "",
      "## Subagents",
      "- `explore` — read-only search subagent. Uses cheaper model (default Haiku 4.5).",
      "- `task` — read+write subagent for delegated work.",
      "- Two modes: `inprocess` (blocking generateText in parent) or `facet` (separate DO peer).",
      "",
      "## Skills",
      "- Three sources: personal (UserControl SQLite), workspace (`.claude/skills/`, `.opencode/skill/`, etc.), built-in (this file).",
      "- Two-stage progressive disclosure: name + description in system prompt, full body via the `skill` tool.",
    ].join("\n"),
  },
  {
    name: "skill-authoring",
    description:
      "How to write a SKILL.md file that loads in Dodo, Claude Code, and OpenCode. Use when asked to create a new skill, document a workflow as a skill, or convert existing instructions into the SKILL.md format.",
    body: [
      "# Authoring SKILL.md",
      "",
      "Skills are markdown files with YAML frontmatter. The format is identical across Dodo, Claude Code, and OpenCode — write once, run everywhere.",
      "",
      "## Required frontmatter",
      "```yaml",
      "---",
      "name: my-skill                # lowercase, hyphens or underscores, max 64 chars",
      "description: One-sentence description that says WHAT and WHEN to use this skill.",
      "---",
      "```",
      "",
      "The `description` is the only thing the model sees at startup — write it like a tool description. Include both *what* the skill does and *when* to invoke it. Max 1024 characters.",
      "",
      "## Body conventions",
      "- Markdown after the frontmatter is the skill body. Loaded on demand by the `skill` tool.",
      "- Reference bundled files by relative path: e.g. `see references/typescript/errors.md`.",
      "- Keep bodies focused — under 32 KB. Larger content goes in `references/`.",
      "",
      "## Bundled resources",
      "Optional sibling directories next to SKILL.md:",
      "- `references/` — lazy-loaded reference docs",
      "- `scripts/` — executable helpers",
      "- `assets/` — static templates (HTML, SVG)",
      "",
      "Bundled files are *listed* by the `skill` tool but never auto-loaded. The model decides what to read.",
      "",
      "## Storing in Dodo",
      "Three places a skill can live:",
      "1. **Personal** (recommended for everyday skills) — created via the `skill_write` MCP tool, stored in UserControl DO.",
      "2. **Workspace** — drop a `.dodo/skills/<name>/SKILL.md` (or `.claude/skills/...`, `.opencode/skill/...`) into the cloned repo.",
      "3. **Built-in** — extend `src/builtin-skills.ts` and rebuild Dodo.",
    ].join("\n"),
  },
  {
    name: "browser-cdp-perf",
    description:
      "ALWAYS load before ANY call to browser_execute or browser_search. Mandatory pre-read — even for 'just one screenshot' or 'just a quick navigate'. Covers Dodo's per-image 3MB hard cap and max-5-images-per-message limit, the 800×600 default viewport that produces cramped mobile-looking screenshots unless you override it, CDP command timing, fresh-browser-per-call session semantics, evaluate() return-shape gotchas, and the fastest patterns for common browser automation. If you are about to invoke browser_execute or browser_search and have not yet loaded this skill, load it first.",
    body: [
      "# Dodo browser tools: faster and safer patterns",
      "",
      "Dodo exposes two browser tools, both backed by Cloudflare Browser Rendering and `@cloudflare/puppeteer` under the hood:",
      "",
      "- **`browser_search`** — run JS against the ~1.7MB CDP spec, server-side. Use this to discover the right CDP method/params/event before executing. Cheap (~50ms), no browser launched.",
      "- **`browser_execute`** — run JS against a live headless Chrome session via a `cdp` helper. **A fresh browser with one blank page is launched per call**, then closed when the function returns. No state persists between calls.",
      "",
      "## Session model (the part that surprises everyone)",
      "",
      "There is no persistent browser. Every `browser_execute` call gets a brand-new Chrome with an empty `about:blank` page, runs your async arrow function, and tears the browser down. Cookies, localStorage, navigation history, viewport overrides — **none of it survives between calls.**",
      "",
      "That means:",
      "- Multi-step workflows (login → navigate → screenshot) must live inside one `browser_execute` call.",
      "- You cannot `browser_execute` to navigate, then `browser_execute` again to screenshot. The second call sees `about:blank`.",
      "- Every call must re-set viewport, re-enable any CDP domain it depends on, re-navigate.",
      "",
      "## Screenshot safety — Dodo-specific limits",
      "",
      "Dodo strips base64 screenshot payloads from `browser_execute`'s tool output text before the model sees it (see `src/browser/tools.ts:extractScreenshotsInPlace`). The screenshot becomes an *attachment* on the assistant message, not a wall of base64 in the tool log. That's the good news.",
      "",
      "The hard limits, from `src/coding-agent.ts`:",
      "- **Per image: `MAX_IMAGE_BASE64_LENGTH = 4_000_000`** (~3MB decoded). Larger images are rejected.",
      "- **Per message: `MAX_IMAGES_PER_MESSAGE = 5`**. The sixth screenshot in one turn is dropped.",
      "",
      "PNG is lossless and uncompressed. A 1440×900 PNG with `deviceScaleFactor:2` (the recommended default for crisp screenshots) easily exceeds 3MB. **For full-page screenshots, use JPEG quality 75 unless you specifically need lossless** — the page can be tall and a `captureBeyondViewport: true` PNG of a content-heavy site routinely blows the cap.",
      "",
      "```js",
      "// Safe full-page",
      "const { data } = await cdp.send('Page.captureScreenshot', {",
      "  format: 'jpeg',",
      "  quality: 75,",
      "  captureBeyondViewport: true,",
      "});",
      "return { screenshot: data, format: 'jpeg', encoding: 'base64' };",
      "",
      "// Dangerous on a tall page",
      "const { data } = await cdp.send('Page.captureScreenshot', {",
      "  format: 'png',",
      "  captureBeyondViewport: true,  // can produce a 5MB+ PNG → rejected",
      "});",
      "```",
      "",
      "If your screenshot comes back rejected or missing from the chat, retry with `format: 'jpeg'` at `quality: 60` — that's almost always enough.",
      "",
      "## Default viewport is 800×600 — override before navigating",
      "",
      "Chrome's headless default viewport in Dodo's launcher is 800×600. Screenshots taken without overriding it look cramped and frequently trigger mobile-styled layouts. Set the viewport **before** `Page.navigate` so styles, media queries, and JS that reads `innerWidth` see the right size:",
      "",
      "```js",
      "await cdp.send('Emulation.setDeviceMetricsOverride', {",
      "  width: 1440, height: 900, deviceScaleFactor: 2, mobile: false,",
      "});",
      "await cdp.send('Page.enable');",
      "await cdp.send('Page.navigate', { url });",
      "// then waitForLoad / sleep / screenshot",
      "```",
      "",
      "Use `deviceScaleFactor: 2` on desktop captures for crisp images on HiDPI displays. Combine with `format: 'jpeg', quality: 75` to keep the file under the 3MB cap.",
      "",
      "## CDP evaluate() return shape",
      "",
      "`Runtime.evaluate` returns `{ result: { value, type }, exceptionDetails? }`. The value lives at `.result.value`. Always check `exceptionDetails` — a script that throws does NOT reject the CDP promise, it returns a result with `exceptionDetails` populated.",
      "",
      "```js",
      "const { result, exceptionDetails } = await cdp.send('Runtime.evaluate', {",
      "  expression: 'document.title',",
      "  returnByValue: true,",
      "  awaitPromise: true,",
      "});",
      "if (exceptionDetails) throw new Error(exceptionDetails.text);",
      "const title = result.value;",
      "```",
      "",
      "`returnByValue: true` is essential — without it you get a remote object handle back, not the JSON value. `awaitPromise: true` lets you write `await fetch(...)` inside the expression.",
      "",
      "## browser_search before browser_execute",
      "",
      "The CDP spec is huge (~1.7MB) and full of footguns. Before composing a `browser_execute` call that uses an unfamiliar CDP method, query the spec:",
      "",
      "```js",
      "// browser_search — find every Page.* command that mentions 'screenshot'",
      "async () => spec.domains",
      "  .find(d => d.name === 'Page').commands",
      "  .filter(c => c.name.toLowerCase().includes('screenshot'))",
      "  .map(c => ({ method: c.method, params: c.parameters?.map(p => p.name) }))",
      "```",
      "",
      "`browser_search` runs server-side, returns plain JSON, and costs no browser launch. Use it to find correct parameter names, event types, and required prerequisites (like `Page.enable` before `Page.navigate` events fire).",
      "",
      "## Batch the whole workflow into one browser_execute",
      "",
      "Because each call launches a fresh browser, splitting work across calls is expensive AND broken (no state persists). Put everything in one async arrow function:",
      "",
      "```js",
      "// GOOD — one browser launch, one screenshot",
      "async () => {",
      "  await cdp.send('Emulation.setDeviceMetricsOverride', {",
      "    width: 1440, height: 900, deviceScaleFactor: 2, mobile: false,",
      "  });",
      "  await cdp.send('Page.enable');",
      "  await cdp.send('Page.navigate', { url: 'https://example.com' });",
      "  await new Promise(r => setTimeout(r, 3000));  // wait for load",
      "  const { data } = await cdp.send('Page.captureScreenshot', {",
      "    format: 'jpeg', quality: 75,",
      "  });",
      "  return { screenshot: data, format: 'jpeg', encoding: 'base64' };",
      "}",
      "",
      "// BAD — second call sees about:blank, screenshot is empty",
      "// Call 1: navigate",
      "// Call 2: screenshot   ← takes a screenshot of about:blank in a NEW browser",
      "```",
      "",
      "## Waiting for navigation / async events",
      "",
      "There is no `wait_for` helper. Two patterns:",
      "",
      "**Listen for a CDP event** (preferred — exact, no arbitrary sleep):",
      "```js",
      "await cdp.send('Page.enable');",
      "const loadFired = new Promise(resolve => {",
      "  // Note: cdp doesn't expose event listeners directly in browser_execute.",
      "  // For most uses, a short sleep after navigate is the practical choice.",
      "});",
      "```",
      "",
      "**Poll a JS condition via Runtime.evaluate** (works when no CDP event fits):",
      "```js",
      "for (let i = 0; i < 30; i++) {",
      "  const { result } = await cdp.send('Runtime.evaluate', {",
      "    expression: 'document.readyState === \"complete\" && !!document.querySelector(\".loaded\")',",
      "    returnByValue: true,",
      "  });",
      "  if (result.value) break;",
      "  await new Promise(r => setTimeout(r, 200));",
      "}",
      "```",
      "",
      "**Arbitrary sleep** is the simplest last resort. `await new Promise(r => setTimeout(r, 3000))` after `Page.navigate` covers most static pages.",
      "",
      "## Loading local HTML",
      "",
      "The headless Chrome runs inside Cloudflare's Browser Rendering — it cannot see `file://` URLs, your local filesystem, or `localhost` from the user's machine. To screenshot HTML you have in your workspace:",
      "",
      "1. **Best: push to a public URL.** Commit + push to GitHub, then `Page.navigate({ url: rawGitHubUrl })`.",
      "2. **`fetch` + `Page.setDocumentContent`.** Have the cloud browser fetch the file, then inject the HTML into the page:",
      "",
      "   ```js",
      "   await cdp.send('Page.enable');",
      "   await cdp.send('Page.navigate', { url: 'about:blank' });",
      "   const { result } = await cdp.send('Runtime.evaluate', {",
      "     expression: `fetch('${rawUrl}').then(r => r.text())`,",
      "     returnByValue: true, awaitPromise: true,",
      "   });",
      "   const html = result.value;",
      "   const { frameTree } = await cdp.send('Page.getFrameTree');",
      "   await cdp.send('Page.setDocumentContent', {",
      "     frameId: frameTree.frame.id, html,",
      "   });",
      "   ```",
      "",
      "   Strip same-origin `/js/*`, `/api/*` references from the HTML first — they'll 404 against `about:blank`. External CDN assets (CSS, libs) load fine.",
      "",
      "3. **`data:text/html;base64,...` URL.** Works for small payloads. Awkward over ~50KB because the data URL goes through the tool-call envelope.",
      "",
      "## Anti-patterns",
      "",
      "| Anti-pattern                                    | Instead                                                              |",
      "| ----------------------------------------------- | -------------------------------------------------------------------- |",
      "| Screenshot at default 800×600 viewport          | `Emulation.setDeviceMetricsOverride` to 1440×900 dpr:2 before navigate |",
      "| `Page.captureScreenshot` with `captureBeyondViewport: true` and PNG on a tall page | Use `format: 'jpeg', quality: 75` for full-page captures |",
      "| Splitting navigate + screenshot across two `browser_execute` calls | Put everything in one async arrow — state doesn't persist between calls |",
      "| Composing CDP code from memory                  | `browser_search` first to find the right method + parameters         |",
      "| Returning `result.value` from `Runtime.evaluate` without checking `exceptionDetails` | Always guard: `if (exceptionDetails) throw new Error(exceptionDetails.text)` |",
      "| Sending 6+ screenshots in one turn              | Hard cap is 5; the rest are dropped silently. Compose composites.    |",
      "| Sleeping for 30s after every navigate           | 2-3s is usually enough for static pages; poll `document.readyState` for dynamic |",
    ].join("\n"),
  },
];

export function listBuiltinSkills(): Skill[] {
  return BUILTIN_SKILLS.map((entry) => ({
    name: entry.name,
    description: entry.description,
    body: entry.body,
    source: "builtin" as const,
    location: `builtin://${entry.name}`,
    assetPaths: [],
    enabled: true,
  }));
}
