import { getUserControlStub } from "./auth";
import type { Env, WorkerRunRecord } from "./types";

/**
 * Parse a GitHub repo URL like https://github.com/owner/repo (optionally .git)
 * into { owner, repo }. Returns null if the URL is not a parseable github.com URL.
 */
export function parseGithubRepo(url: string): { owner: string; repo: string } | null {
  try {
    const u = new URL(url);
    if (u.hostname !== "github.com") return null;
    const parts = u.pathname.replace(/\.git$/, "").split("/").filter(Boolean);
    if (parts.length < 2) return null;
    return { owner: parts[0], repo: parts[1] };
  } catch {
    return null;
  }
}

async function resolveGithubToken(env: Env, ownerEmail?: string): Promise<string | undefined> {
  if (ownerEmail) {
    try {
      const stub = getUserControlStub(env, ownerEmail);
      const response = await stub.fetch("https://user-control/internal/secret/github_token", {
        headers: { "x-owner-email": ownerEmail },
      });
      if (response.ok) {
        const { value } = (await response.json()) as { value: string };
        if (value) return value;
      }
    } catch {
      // Fall through to env
    }
  }
  return env.GITHUB_TOKEN;
}

/**
 * Build a PR body from a completed worker run. Includes summary, verification
 * details, and dispatch metadata so reviewers know it's agent-authored.
 */
export function buildPrBody(run: WorkerRunRecord): string {
  const lines: string[] = [
    "## Summary",
    "",
    `Auto-generated by Dodo worker run \`${run.id}\`.`,
    "",
    run.commitMessage ?? "",
    "",
    "## Metadata",
    "",
    `- Branch: \`${run.branch}\``,
    `- Base: \`${run.baseBranch}\``,
    `- Session: \`${run.sessionId}\``,
    `- Strategy: \`${run.strategy}\``,
  ];
  if (run.verification) {
    lines.push(`- Verification: \`${JSON.stringify(run.verification)}\``);
  }
  lines.push(
    "",
    "---",
    "",
    "🤖 Drafted via `dodo_dispatch_repo_prompt`.",
  );
  return lines.join("\n");
}

/**
 * Create a draft pull request on GitHub for a completed worker run.
 * Returns the PR URL, or null if creation failed (missing token, API error, etc.).
 * Failures are logged but never thrown — PR creation must not break the run.
 */
export async function createDraftPrForRun(
  env: Env,
  run: WorkerRunRecord,
  ownerEmail?: string,
): Promise<string | null> {
  try {
    const parsed = parseGithubRepo(run.repoUrl);
    if (!parsed) return null;
    const token = await resolveGithubToken(env, ownerEmail);
    if (!token) return null;

    const response = await fetch(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}/pulls`, {
      method: "POST",
      headers: {
        "Accept": "application/vnd.github+json",
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "dodo-dispatch",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: run.title,
        head: run.branch,
        base: run.baseBranch,
        body: buildPrBody(run),
        draft: true,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.warn(`[auto-pr] GitHub API returned ${response.status}:`, errorText.slice(0, 500));
      return null;
    }

    const data = (await response.json()) as { html_url: string };
    return data.html_url ?? null;
  } catch (err) {
    console.warn("[auto-pr] failed to create PR:", err);
    return null;
  }
}
