import { log } from "./logger";
import { parseRemoteSpec } from "./repos";
import { resolveProviderToken } from "./git-auth";
import type { Env, WorkerRunRecord } from "./types";

/** Timeout for PR/MR creation HTTP calls. Workers DOs can stall indefinitely
 *  on a misbehaving upstream — bound it so a single tool call can't hold a
 *  turn open forever. */
const PR_FETCH_TIMEOUT_MS = 20_000;

/**
 * Parse a GitHub repo URL like https://github.com/owner/repo (optionally .git)
 * into { owner, repo }. Returns null if the URL is not a parseable github.com URL.
 */
export function parseGithubRepo(url: string): { owner: string; repo: string } | null {
  try {
    const u = new URL(url);
    if (u.hostname !== "github.com") return null;
    const parts = u.pathname.replace(/\.git$/, "").split("/").filter(Boolean);
    if (parts.length < 2) return null;
    return { owner: parts[0], repo: parts[1] };
  } catch {
    return null;
  }
}

/**
 * Build a PR body from a completed worker run. Includes summary, verification
 * details, and dispatch metadata so reviewers know it's agent-authored.
 */
export function buildPrBody(run: WorkerRunRecord): string {
  const lines: string[] = [
    "## Summary",
    "",
    `Auto-generated by Dodo worker run \`${run.id}\`.`,
    "",
    run.commitMessage ?? "",
    "",
    "## Metadata",
    "",
    `- Branch: \`${run.branch}\``,
    `- Base: \`${run.baseBranch}\``,
    `- Session: \`${run.sessionId}\``,
    `- Strategy: \`${run.strategy}\``,
  ];
  if (run.verification) {
    lines.push(`- Verification: \`${JSON.stringify(run.verification)}\``);
  }
  lines.push(
    "",
    "---",
    "",
    "🤖 Drafted via `dodo_dispatch_repo_prompt`.",
  );
  return lines.join("\n");
}

/**
 * Create a draft pull request on GitHub for a completed worker run.
 * Returns the PR URL, or null if creation failed (missing token, API error, etc.).
 * Failures are logged but never thrown — PR creation must not break the run.
 */
export async function createDraftPrForRun(
  env: Env,
  run: WorkerRunRecord,
  ownerEmail?: string,
): Promise<string | null> {
  try {
    const parsed = parseGithubRepo(run.repoUrl);
    if (!parsed) return null;
    const token = await resolveProviderToken(env, "github", ownerEmail);
    if (!token) return null;

    const response = await fetch(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}/pulls`, {
      method: "POST",
      headers: {
        "Accept": "application/vnd.github+json",
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "dodo-dispatch",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: run.title,
        head: run.branch,
        base: run.baseBranch,
        body: buildPrBody(run),
        draft: true,
      }),
      signal: AbortSignal.timeout(PR_FETCH_TIMEOUT_MS),
    });

    if (!response.ok) {
      const errorText = await response.text();
      log("warn", "auto-pr: GitHub API returned non-OK", { status: response.status, body: errorText.slice(0, 500) });
      return null;
    }

    const data = (await response.json()) as { html_url: string };
    return data.html_url ?? null;
  } catch (err) {
    log("warn", "auto-pr: failed to create PR", { error: err instanceof Error ? err.message : String(err) });
    return null;
  }
}

// ─── Interactive PR/MR creation (for the pr_create tool) ───

export interface CreatePullRequestInput {
  /** Remote URL (https or ssh) — used to detect provider and parse owner/repo. */
  remoteUrl: string;
  /** Source branch (head ref). */
  head: string;
  /** Target branch (base ref). */
  base: string;
  /** PR/MR title. */
  title: string;
  /** Optional body. Pass through as-is. */
  body?: string;
  /** Open as draft. Defaults to true to match Dodo dispatch behavior. */
  draft?: boolean;
}

export interface CreatePullRequestSuccess {
  ok: true;
  url: string;
  number: number;
  provider: "github" | "gitlab";
}

export interface CreatePullRequestFailure {
  ok: false;
  error: string;
  provider?: "github" | "gitlab";
}

export type CreatePullRequestResult = CreatePullRequestSuccess | CreatePullRequestFailure;

/**
 * Create a pull request (GitHub) or merge request (GitLab). Auto-detects the
 * provider from the remote URL. Uses the owner's per-user encrypted token
 * (`github_token` / `gitlab_token`), falling back to env vars.
 *
 * Unlike `createDraftPrForRun`, this function THROWS on bad input but returns
 * a structured `{ ok: false, error }` for API failures so the calling tool can
 * surface a useful message to the agent.
 */
export async function createPullRequest(
  env: Env,
  input: CreatePullRequestInput,
  ownerEmail?: string,
): Promise<CreatePullRequestResult> {
  const parsed = parseRemoteSpec(input.remoteUrl);
  if (!parsed) {
    return {
      ok: false,
      error: `Could not parse remote URL '${input.remoteUrl}'. Only github.com and gitlab.com / gitlab.cfdata.org are supported.`,
    };
  }

  const draft = input.draft ?? true;
  const token = await resolveProviderToken(env, parsed.provider, ownerEmail);
  if (!token) {
    return {
      ok: false,
      error: `No ${parsed.provider} token available. Add it via the secrets UI (key '${parsed.provider}_token') or set ${parsed.provider === "github" ? "GITHUB_TOKEN" : "GITLAB_TOKEN"} on the worker.`,
      provider: parsed.provider,
    };
  }

  if (parsed.provider === "github") {
    return createGithubPr({ env: env, parsed, input, token, draft });
  }
  return createGitlabMr({ parsed, input, token, draft });
}

/**
 * Add a hint to common 422 errors so the agent can self-correct.
 *
 * GitHub returns 422 for both "PR already exists" and "head branch not
 * found" — both of which the agent can fix without escalating to the user
 * (push first, or check existing PRs). Hint nudges them in that direction.
 */
function annotatePrError(provider: "github" | "gitlab", status: number, body: string): string {
  const base = `${provider === "github" ? "GitHub" : "GitLab"} API returned ${status}: ${body.slice(0, 300)}`;
  if (status !== 422 && status !== 400) return base;
  const lower = body.toLowerCase();
  if (lower.includes("already exists") || lower.includes("a pull request already exists")) {
    return `${base}\n\nHint: a PR/MR may already exist between this head and base. Check the repo's existing PRs.`;
  }
  if (lower.includes("not found") || lower.includes("head ref") || lower.includes("source_branch")) {
    return `${base}\n\nHint: the head branch may not be on the remote yet. Push it first with git_push_checked, or pass a branch name that exists on the remote.`;
  }
  if (lower.includes("base") || lower.includes("target_branch")) {
    return `${base}\n\nHint: the base/target branch may not exist on the remote. Pass an explicit base (e.g. base: 'master' or 'staging') if 'main' isn't the default.`;
  }
  return base;
}

async function createGithubPr(args: {
  env: Env;
  parsed: NonNullable<ReturnType<typeof parseRemoteSpec>>;
  input: CreatePullRequestInput;
  token: string;
  draft: boolean;
}): Promise<CreatePullRequestResult> {
  const { parsed, input, token, draft } = args;
  try {
    const response = await fetch(
      `https://api.github.com/repos/${encodeURIComponent(parsed.owner)}/${encodeURIComponent(parsed.repo)}/pulls`,
      {
        method: "POST",
        headers: {
          "Accept": "application/vnd.github+json",
          "Authorization": `Bearer ${token}`,
          "Content-Type": "application/json",
          "User-Agent": "dodo-agent",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({
          title: input.title,
          head: input.head,
          base: input.base,
          body: input.body ?? "",
          draft,
        }),
        signal: AbortSignal.timeout(PR_FETCH_TIMEOUT_MS),
      },
    );
    if (!response.ok) {
      const text = await response.text().catch(() => "");
      return {
        ok: false,
        error: annotatePrError("github", response.status, text),
        provider: "github",
      };
    }
    const data = (await response.json()) as { html_url?: string; number?: number };
    if (!data.html_url || typeof data.number !== "number") {
      return { ok: false, error: "GitHub returned an unexpected response", provider: "github" };
    }
    return { ok: true, url: data.html_url, number: data.number, provider: "github" };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const friendly = err instanceof Error && err.name === "TimeoutError"
      ? `GitHub API request timed out after ${PR_FETCH_TIMEOUT_MS / 1000}s. Try again, or fall back to the compare URL.`
      : message;
    return { ok: false, error: friendly, provider: "github" };
  }
}

async function createGitlabMr(args: {
  parsed: NonNullable<ReturnType<typeof parseRemoteSpec>>;
  input: CreatePullRequestInput;
  token: string;
  draft: boolean;
}): Promise<CreatePullRequestResult> {
  const { parsed, input, token, draft } = args;
  try {
    // GitLab marks MRs as draft via title prefix "Draft: ".
    const title = draft && !input.title.startsWith("Draft:") ? `Draft: ${input.title}` : input.title;
    const project = encodeURIComponent(parsed.fullName);
    const response = await fetch(
      `https://${parsed.host}/api/v4/projects/${project}/merge_requests`,
      {
        method: "POST",
        headers: {
          "Accept": "application/json",
          "Content-Type": "application/json",
          "PRIVATE-TOKEN": token,
          "User-Agent": "dodo-agent",
        },
        body: JSON.stringify({
          source_branch: input.head,
          target_branch: input.base,
          title,
          description: input.body ?? "",
        }),
        signal: AbortSignal.timeout(PR_FETCH_TIMEOUT_MS),
      },
    );
    if (!response.ok) {
      const text = await response.text().catch(() => "");
      return {
        ok: false,
        error: annotatePrError("gitlab", response.status, text),
        provider: "gitlab",
      };
    }
    const data = (await response.json()) as { web_url?: string; iid?: number };
    if (!data.web_url || typeof data.iid !== "number") {
      return { ok: false, error: "GitLab returned an unexpected response", provider: "gitlab" };
    }
    return { ok: true, url: data.web_url, number: data.iid, provider: "gitlab" };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const friendly = err instanceof Error && err.name === "TimeoutError"
      ? `GitLab API request timed out after ${PR_FETCH_TIMEOUT_MS / 1000}s. Try again, or fall back to the compare URL.`
      : message;
    return { ok: false, error: friendly, provider: "gitlab" };
  }
}

// ─── Create a fresh GitHub repo (for the publish_to_github tool) ───

export interface CreateGithubRepoInput {
  /** Repo name. Must match GitHub's naming rules (alphanumerics, `-`, `_`, `.`). */
  name: string;
  /** Org to create the repo under. If omitted, the repo is created on the
   *  authenticated user's account. */
  owner?: string;
  /** Visibility. Defaults to private — Dodo sessions are personal scratch
   *  spaces and shouldn't accidentally publish to the world. */
  private?: boolean;
  /** Optional description shown on the GitHub repo page. */
  description?: string;
}

export interface CreateGithubRepoSuccess {
  ok: true;
  /** `https://github.com/<owner>/<repo>` */
  htmlUrl: string;
  /** `https://github.com/<owner>/<repo>.git` — the URL to push to. */
  cloneUrl: string;
  owner: string;
  name: string;
  private: boolean;
}

export interface CreateGithubRepoFailure {
  ok: false;
  error: string;
  /** True when the failure is "name already taken" — the caller may want to
   *  retry with a suffix. (`POST /user/repos` returns 422 in that case.) */
  nameTaken?: boolean;
}

export type CreateGithubRepoResult = CreateGithubRepoSuccess | CreateGithubRepoFailure;

const REPO_NAME_RE = /^[a-zA-Z0-9._-]+$/;

/**
 * Create a fresh GitHub repository. The token must have:
 * - `repo` scope (classic PAT), OR
 * - `Contents: Write` + `Administration: Write` (fine-grained PAT).
 *
 * Returns a structured `{ ok: true, cloneUrl }` on success so the caller can
 * configure a remote and push to it.
 */
export async function createGithubRepo(
  env: Env,
  input: CreateGithubRepoInput,
  ownerEmail?: string,
): Promise<CreateGithubRepoResult> {
  if (!REPO_NAME_RE.test(input.name)) {
    return {
      ok: false,
      error: `Invalid repo name '${input.name}'. GitHub allows alphanumerics, '-', '_', and '.' only.`,
    };
  }

  const token = await resolveProviderToken(env, "github", ownerEmail);
  if (!token) {
    return {
      ok: false,
      error: "No github token available. Add it via the secrets UI (key 'github_token') or set GITHUB_TOKEN on the worker. The token must have 'repo' scope (classic) or 'Administration: Write' (fine-grained) to create repos.",
    };
  }

  const isPrivate = input.private ?? true;
  const url = input.owner
    ? `https://api.github.com/orgs/${encodeURIComponent(input.owner)}/repos`
    : "https://api.github.com/user/repos";

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Accept": "application/vnd.github+json",
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "dodo-agent",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        name: input.name,
        private: isPrivate,
        description: input.description,
        // Don't auto-init — we're about to push our own history.
        auto_init: false,
      }),
      signal: AbortSignal.timeout(PR_FETCH_TIMEOUT_MS),
    });

    if (!response.ok) {
      const text = await response.text().catch(() => "");
      const lower = text.toLowerCase();
      const nameTaken = response.status === 422 && (lower.includes("already exists") || lower.includes("name already"));
      let error = `GitHub API returned ${response.status}: ${text.slice(0, 300)}`;
      if (nameTaken) {
        error += "\n\nHint: a repo with that name already exists. Try a different name, or pass `owner` to create under an org.";
      } else if (response.status === 401 || response.status === 403) {
        error += "\n\nHint: the token may be missing the 'repo' scope (classic PAT) or 'Administration: Write' (fine-grained PAT). Check the token's permissions and try again.";
      } else if (response.status === 404 && input.owner) {
        error += `\n\nHint: the org '${input.owner}' does not exist or your token doesn't have access to it.`;
      }
      return { ok: false, error, nameTaken };
    }

    const data = (await response.json()) as {
      html_url?: string;
      clone_url?: string;
      private?: boolean;
      owner?: { login?: string };
      name?: string;
    };
    if (!data.html_url || !data.clone_url || !data.owner?.login || !data.name) {
      return { ok: false, error: "GitHub returned an unexpected response (missing url/owner/name)." };
    }
    return {
      ok: true,
      htmlUrl: data.html_url,
      cloneUrl: data.clone_url,
      owner: data.owner.login,
      name: data.name,
      private: data.private ?? isPrivate,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const friendly = err instanceof Error && err.name === "TimeoutError"
      ? `GitHub API request timed out after ${PR_FETCH_TIMEOUT_MS / 1000}s.`
      : message;
    return { ok: false, error: friendly };
  }
}

// ─── GitHub Actions verify gate ───

interface VerifyTriggerResult {
  runId: string;
  htmlUrl: string;
}

interface VerifyPollResult {
  conclusion: "success" | "failure" | "cancelled" | "timed_out" | "action_required" | "neutral" | "skipped" | "stale" | "startup_failure";
  htmlUrl: string;
  /** ISO timestamp of when the workflow run finished. */
  completedAt: string | null;
}

/**
 * Trigger the verify workflow for a branch via `workflow_dispatch`.
 *
 * Returns the newly-created workflow run so the caller can persist the id
 * and poll for completion.
 *
 * `workflow_dispatch` is asynchronous — GitHub responds 204 before the run
 * exists. We then query the runs list to find the one we just triggered.
 *
 * Run identification uses two signals to avoid grabbing an unrelated run
 * (e.g. a concurrent human-dispatched run for the same branch):
 *
 *   1. **head_sha match** (primary). Before dispatching, we look up the
 *      branch's current tip. A `workflow_dispatch` run records that sha as
 *      `head_sha`, so a match is authoritative.
 *   2. **created_at window** (secondary). Fallback when the branch sha
 *      lookup fails. Tight 2-second window accepts real NTP skew while
 *      rejecting runs from humans dispatching the same workflow moments
 *      earlier.
 */
export async function triggerVerifyWorkflow(input: {
  env: Env;
  run: WorkerRunRecord;
  ownerEmail?: string;
}): Promise<VerifyTriggerResult | null> {
  const { env, run, ownerEmail } = input;
  if (!run.verifyWorkflow) return null;
  const parsed = parseGithubRepo(run.repoUrl);
  if (!parsed) return null;
  const token = await resolveProviderToken(env, "github", ownerEmail);
  if (!token) return null;

  // Resolve the branch's current head sha so we can match runs authoritatively.
  const expectedHeadSha = await fetchBranchHeadSha({ owner: parsed.owner, repo: parsed.repo, branch: run.branch, token });

  const triggerUrl = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}/actions/workflows/${encodeURIComponent(run.verifyWorkflow)}/dispatches`;
  const triggeredAt = Date.now();
  const triggerRes = await fetch(triggerUrl, {
    method: "POST",
    headers: ghHeaders(token),
    body: JSON.stringify({ ref: run.branch }),
  });

  if (!triggerRes.ok) {
    const errorText = await triggerRes.text();
    console.warn(`[verify-gate] workflow_dispatch failed ${triggerRes.status}:`, errorText.slice(0, 500));
    return null;
  }

  // Find the run we just created. GitHub's API can take a second or two to
  // materialize the run — poll the runs list briefly.
  for (let attempt = 0; attempt < 10; attempt++) {
    await sleep(500 + attempt * 500);
    const listUrl = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}/actions/workflows/${encodeURIComponent(run.verifyWorkflow)}/runs?branch=${encodeURIComponent(run.branch)}&event=workflow_dispatch&per_page=5`;
    const listRes = await fetch(listUrl, { headers: ghHeaders(token) });
    if (!listRes.ok) continue;
    const listData = (await listRes.json()) as { workflow_runs: Array<{ id: number; html_url: string; created_at: string; head_sha?: string }> };
    const candidate = listData.workflow_runs?.find((r) => {
      // Primary: head_sha match is authoritative if we have the expected sha.
      if (expectedHeadSha && r.head_sha === expectedHeadSha) return true;
      if (expectedHeadSha) return false; // have sha, must match — don't fall through to time window

      // Fallback: tight time window. ±2s covers NTP skew; tighter than the
      // typical human reaction time between dispatches.
      const createdMs = Date.parse(r.created_at);
      return Number.isFinite(createdMs) && createdMs >= triggeredAt - 2_000;
    });
    if (candidate) {
      return { runId: String(candidate.id), htmlUrl: candidate.html_url };
    }
  }

  console.warn("[verify-gate] workflow dispatched but run id not found within 5s");
  return null;
}

/**
 * Look up the current head sha for a branch. Returns null on any failure so
 * the caller can fall back to time-window matching.
 */
async function fetchBranchHeadSha(input: {
  owner: string;
  repo: string;
  branch: string;
  token: string;
}): Promise<string | null> {
  try {
    const url = `https://api.github.com/repos/${input.owner}/${input.repo}/branches/${encodeURIComponent(input.branch)}`;
    const res = await fetch(url, { headers: ghHeaders(input.token) });
    if (!res.ok) return null;
    const data = (await res.json()) as { commit?: { sha?: string } };
    return data.commit?.sha ?? null;
  } catch {
    return null;
  }
}

/**
 * Fetch the current status of a workflow run. Returns a poll result only if
 * the run has reached a terminal state; returns null while still running.
 */
export async function pollVerifyWorkflow(input: {
  env: Env;
  run: WorkerRunRecord;
  ownerEmail?: string;
}): Promise<VerifyPollResult | null> {
  const { env, run, ownerEmail } = input;
  if (!run.verifyWorkflowRunId) return null;
  const parsed = parseGithubRepo(run.repoUrl);
  if (!parsed) return null;
  const token = await resolveProviderToken(env, "github", ownerEmail);
  if (!token) return null;

  const url = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}/actions/runs/${encodeURIComponent(run.verifyWorkflowRunId)}`;
  const res = await fetch(url, { headers: ghHeaders(token) });
  if (!res.ok) {
    console.warn(`[verify-gate] poll failed ${res.status}`);
    return null;
  }

  const data = (await res.json()) as {
    status: string;
    conclusion: string | null;
    html_url: string;
    updated_at: string;
  };

  // status is one of: queued, in_progress, completed
  if (data.status !== "completed") return null;
  const conclusion = (data.conclusion ?? "failure") as VerifyPollResult["conclusion"];
  return { conclusion, htmlUrl: data.html_url, completedAt: data.updated_at };
}

function ghHeaders(token: string): Record<string, string> {
  return {
    "Accept": "application/vnd.github+json",
    "Authorization": `Bearer ${token}`,
    "Content-Type": "application/json",
    "User-Agent": "dodo-dispatch",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
